# Generated by Django 3.2.11 on 2024-01-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='species_chi',
        ),
    ]
